[package]
name = "problem770"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_float_eq = "1.1.3"
dashu-float = "0.4.3"
rug = "1.24.0"
